### ISSUE TITLE
subprocess installed post-installation script returned error exit status 1

### ISSUE THREAD

**Issue by sergiobenrocha2** [prey/prey-node-client#129] opened 2015-04-30 21:52 UTC
Xubuntu 14.04 amd64, prey 1.3.9:

```
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 999 and gid 998
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.3.9/prey.conf.default
Setting up this as current...
No version is set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
Sweet! Please run `prey config gui` to finish installation.
Voila! All good.
dpkg: error processing package prey (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 prey
```

**Comment by sergiobenrocha2** [comment] 2015-04-30 21:56
And for some reason, "Update location" and "Sound alarm" didn't work in the first install (I updated, without purge the last package). So now I purge the package and everything in /usr/lib/prey, install again, and these feature worked, but with this error in the install.

**Comment by lemavri** [comment] 2015-05-01 01:02
Hello @sergiobenrocha2, thanks for your feedback. The issue you report might be related to this: http://askubuntu.com/questions/611777/how-to-resolve-dpkg-error-configure/611975#611975, which I'll be taking care of really soon. 

I'll let you know when it's fixed in case you want to try it out for yourself.

**Comment by sergiobenrocha2** [comment] 2015-05-17 14:29
Seems it's fixed in 1.3.10 ?

**Comment by lemavri** [comment] 2015-05-17 15:12
I indeed changed the POSTINST file of the `.deb` package to make use of `gksu`. This makes the installation to run smooth when using `dpkg -i` and `apt-get install -f` afterwards to install the new `gksu` dependency, but when you install using the Ubuntu Software Center you still might get an error, which I'm hoping to fix really soon.

How are you installing Prey?

**Comment by sergiobenrocha2** [comment] 2015-05-17 18:16
Download & dpkg -i

**Comment by lemavri** [comment] 2015-05-18 13:28
If you were not able to reproduce the problem in 1.3.10, I'll go ahead and close the issue. Feel free to open it again if you have the same problem again.

**Closed by lemavri** 2015-05-18 13:28 UTC

**Comment by dcrystalj** [comment] 2016-05-17 11:04
I have same problem on ubuntu 16.04. I downloaded ```prey_1.5.1_amd64.deb``` and run ```sudo dpkg -i prey_1.5.1_amd64.deb```
it didn't met dependencies so i run ```sudo apt-get -f install```

at the end i get error
```
chowning /etc/prey to uid 999 and gid 999
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 999 and gid 999
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.5.1/prey.conf.default
Setting up this as current...
Warning: This version is already set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.

dpkg: error processing package prey (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 prey
```

**Comment by john-francis96** [comment] 2016-05-19 09:05
I'm having this exact problem as well. I'm using Ubuntu 16.04 LTS and prey version 1.5.1

**Comment by ez2torta** [comment] 2016-05-27 12:43
Having same problem, running Linux Mint 17.3 Rosa

**Comment by raliste** [comment] 2016-05-27 14:20
Guys, we have finally sat down, put our things together, detected the problem and already working on a fix. Should be ready by next week.
