### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by dlford** [prey/prey-node-client#370] opened 2018-05-25 02:57 UTC
I'm using Fedora 28 on an HP Spectre x360, running the command `sudo npm install -g prey` gives the following output:

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/tomas/decompress-zip.git /root/.npm/_cacache/tmp/git-clone-898aa2be
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-898aa2be': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-25T02_54_24_746Z-debug.log

```

**Comment by janus-reith** [comment] 2018-10-21 16:50
duplicate of [330](https://github.com/prey/prey-node-client/issues/330)
I'm facing the same issue.

**Closed** 2022-05-25 16:03 UTC
