### ISSUE TITLE
Actions don't persist after system restart (HS:actions-persistence)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#77] opened 2015-01-27 20:22 UTC
## Problem

[Version 1.3.6](https://github.com/prey/prey-node-client/releases/tag/v1.3.6) introduced persistence for triggered actions even when machines are shut down. This is specially useful for *Lock*. For now it's broken.

Here's the log after system restart.

```
  ████████████████ ████████████████ ████████████████ ██            ██
  ██            ██ ██               ██            ██ ██            ██
  ██            ██ ██               ████████████████ ██            ██
  ██            ██ ██               ██               ██            ██
  ████████████████ ██               ████████████████ ████████████████
  ██                                                               ██
  ██                                                 ████████████████

  PREY 1.3.6 spreads its wings!
  Current time: Tue Jan 27 2015 16:46:40 GMT-0300 (Hora verano Sudamérica Pacífico)
  Running with PID 1744 as REDEEMER_ over Node.js v0.10.32 on a x64 windows system (6.2.9200)

    error Tue, 27 Jan 2015 19:46:41 GMT Error: getaddrinfo ENOTFOUND
   notice Tue, 27 Jan 2015 19:46:41 GMT Lost connection. Trying to connect...
     info Tue, 27 Jan 2015 19:46:41 GMT [triggers] Watching: connection, network, power
     info Tue, 27 Jan 2015 19:46:41 GMT [actions] Starting trigger: connection
     info Tue, 27 Jan 2015 19:46:41 GMT [actions] Running: connection
     info Tue, 27 Jan 2015 19:46:41 GMT [actions] Starting trigger: network
     info Tue, 27 Jan 2015 19:46:41 GMT [actions] Starting trigger: power
     info Tue, 27 Jan 2015 19:46:50 GMT [control-panel] Queuing check-ins every 20 minutes.
   notice Tue, 27 Jan 2015 19:46:50 GMT [control-panel] Checking for existing port mappings...
     info Tue, 27 Jan 2015 19:46:50 GMT Plugin loaded: control-panel
     info Tue, 27 Jan 2015 19:46:50 GMT 1 plugins loaded with 0 errors.
     info Tue, 27 Jan 2015 19:46:50 GMT Initialized.
     info Tue, 27 Jan 2015 19:46:50 GMT [control-panel] Queuing check-ins every 0.5 minutes.
     info Tue, 27 Jan 2015 19:46:50 GMT [actions] Running: network
     info Tue, 27 Jan 2015 19:46:50 GMT [actions] Running: power
     warn Tue, 27 Jan 2015 19:46:54 GMT [control-panel] Unable to sync settings.
    error Tue, 27 Jan 2015 19:46:54 GMT Error: Network seems to be down. Check your connection and try again.
     info Tue, 27 Jan 2015 19:46:55 GMT [control-panel] No previously mapped ports found.
     info Tue, 27 Jan 2015 19:47:13 GMT [providers] private_ip already in progress.
   notice Tue, 27 Jan 2015 19:47:13 GMT [control-panel] Checking for existing port mappings...
    error Tue, 27 Jan 2015 19:47:14 GMT Error: Command failed: 
     info Tue, 27 Jan 2015 19:47:15 GMT [reports] Gathering status report.
     info Tue, 27 Jan 2015 19:47:18 GMT [control-panel] No previously mapped ports found.
     info Tue, 27 Jan 2015 19:47:18 GMT [control-panel] Attempting to map external port 30302
     info Tue, 27 Jan 2015 19:47:30 GMT [reports] Report gathered: status
     info Tue, 27 Jan 2015 19:47:30 GMT [control-panel] Posting event
     info Tue, 27 Jan 2015 19:47:33 GMT [control-panel] Got 200 response: Ok mate.

    error Tue, 27 Jan 2015 19:48:07 GMT [control-panel] Unable to map port: Could not locate gateway on time.
     warn Tue, 27 Jan 2015 19:50:50 GMT [control-panel] Got 1 commands.
     info Tue, 27 Jan 2015 19:50:52 GMT [reports] Gathering status report.
     info Tue, 27 Jan 2015 19:50:53 GMT [reports] Report gathered: status
     info Tue, 27 Jan 2015 19:50:53 GMT [control-panel] Posting data
     info Tue, 27 Jan 2015 19:50:54 GMT [control-panel] Got 200 response: OK
```

My machine runs Windows 8.1 64 bits, by the way. The customer's computer is a MacBook Air running OS X Yosemite 10.10.

## How it was detected.

A customer reported the problem. I was able to replicate it immediately.

## Suggestion

Make sure that lock persists as long as it's enabled on the user's [Prey account](https://panel.preyproject.com/app).

## References

- https://secure.helpscout.net/conversation/67917029/12569/

**Comment by fanuneza** [comment] 2015-02-03 19:55
Any news about this, guys? @lemavri?

**Comment by lemavri** [comment] 2015-02-03 20:08
I'll take a look.

**Comment by lemavri** [comment] 2015-02-11 19:57
@fanuneza Does this happen when forcing shutdown or under regular reboots/shutdown?

**Comment by fanuneza** [comment] 2015-02-11 20:03
I guess it's forced shut down.

![one does not simply](https://cloud.githubusercontent.com/assets/401279/6155168/dc5e70f2-b20f-11e4-8e3c-c077ff1a3b19.jpg)

**Comment by lemavri** [comment] 2015-02-11 20:25
@fanuneza unless #70. Also, other actions besides lock can also be persisted. i.e.: alert.

**Comment by fanuneza** [comment] 2015-02-11 20:26
I understand that alarm is a run-once instruction, isn't it?

**Comment by lemavri** [comment] 2015-02-11 20:26
Alarm is, alert is not.

**Comment by fanuneza** [comment] 2015-02-11 20:28
You're right. *Alarm*, *alert*...

![moss-brilliant](https://cloud.githubusercontent.com/assets/401279/6155610/68152a0c-b213-11e4-9c36-d615340a578d.gif)

**Comment by fanuneza** [comment] 2015-02-18 15:47
Any news about this one, @lemavri?

**Comment by lemavri** [comment] 2015-02-18 15:49
Not yet. It's one of the first bug I'll focus once I start fixing things.

**Comment by fanuneza** [comment] 2015-02-18 16:01
Is there an ETA for that?

**Comment by camilaburgos** [comment] 2015-03-09 19:21
Is there any news regarding this bug @lemavri ?

**Comment by lemavri** [comment] 2015-03-09 19:30
Last friday we were not able to reproduce the issue, testing in two different laptops with Windows 8.1. I'll give it another try after I'm done with the release of v1.3.7.

**Comment by lemavri** [comment] 2015-03-09 19:59
Actually, I correct myself. We were able to reproduce the issue in @fanuneza laptop. I've also identified two different issues related to this, that I'll document ASAP.

**Comment by camilaburgos** [comment] 2015-04-30 13:40
Please, take a look into this as soon as possible. A new customer is affected by this problem.

**Comment by lemavri** [comment] 2015-07-17 15:59
There was a server-side issue with running actions. Most likely this is fixed by now, I'll try to replicate and if I can't I'll close the issue.

**Comment by camilaburgos** [comment] 2015-09-25 13:06
This keeps happening: 

- https://secure.helpscout.net/conversation/120891460/30510/

**Closed** 2016-07-18 21:31 UTC
Labels: bug, priority: high
