### ISSUE TITLE
please add Parabola GNU/Linux to your OS list

### ISSUE THREAD

**Issue by shackra** [prey/prey-node-client#105] opened 2015-03-21 23:25 UTC
```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Parabola
Description:    Parabola GNU/Linux-libre
Release:        rolling
Codename:       n/a
```

**Comment by lemavri** [comment] 2015-03-23 12:54
The distro has been added. Could you please check if it's working now and let me know how this goes? Thanks.

**Comment by shackra** [comment] 2015-03-24 00:12
thank you!

Everything is good :+1:

**Comment by shackra** [comment] 2015-03-24 05:07
Wait, I don't have available other actions than sending a message. Why?
![screenshot-panel preyproject com 2015-03-23 23-07-15](https://cloud.githubusercontent.com/assets/1055216/6796068/664d4e9e-d1b1-11e4-9d53-d71079bc1b6a.png)

**Comment by fanuneza** [comment] 2015-03-24 10:32
@shackra I can confirm that also happened to me last time I tried [elementary](http://elementaryos.org). It should be filed as a new issue, though.

**Comment by lemavri** [comment] 2015-03-25 14:40
I will check the actions support for your distro and get back to you.

**Comment by shackra** [comment] 2015-03-26 05:38
Believe me, every action works. I know that because I changed the lsb_release file with Arch Linux's data, registered my laptop and played for a while with the actions.

**Comment by lemavri** [comment] 2015-03-26 12:52
Oh, I know, what I meant with my previous comment is that I'll check what are the definitions in our server-side for the supported actions in Parabola (and Arch).

**Comment by lemavri** [comment] 2015-03-26 14:53
I found the cause of the issue and the fix is being deployed as of right now. This will fix also actions for the following distros:

- Mint
- Elementary
- Manjaro
- Mer

**Comment by boris** [comment] 2015-03-26 15:02
@shackra we just deployed the fix for this issue. Please verify and fell free to re-open the issue if it doesn't work as expected.

**Closed by boris** 2015-03-26 15:02 UTC
Labels: enhancement, priority: critical

**Comment by shackra** [comment] 2015-03-26 17:25
Ok!

El 26 de marzo de 2015 09:02:48 CST, Boris Quiroz <notifications@github.com> escribió:
>@shackra we just deployed the fix for this issue. Please verify and
>fell free to re-open the issue if it doesn't work as expected. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/prey/prey-node-client/issues/105#issuecomment-86556668

-- 
Enviado desde mi teléfono con K-9 Mail.

**Comment by netnut404** [comment] 2015-03-27 18:08
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.0.1406 (Core) 
Release:	7.0.1406
Codename:	Core

**Comment by shackra** [comment] 2015-03-28 05:47
@netnut404 better post a new issue...
