### ISSUE TITLE
Can't install on OS X El Capitan 10.11

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-node-client#147] opened 2015-07-23 19:30 UTC
## Problem

On install, Prey throws the following line on OSX El Capitan 10.11

Humax-Living-Room:~ stewartdunn$ /usr/lib/prey/current/bin/prey config gui -f

-bash: /usr/lib/prey/current/bin/prey: No such file or directory

Humax-Living-Room:~ stewartdunn$

## How it was detected.

User feedback.

## References

https://secure.helpscout.net/conversation/104576542/25324/

**Comment by lemavri** [comment] 2015-07-23 19:34
This is because Prey is not installed. The issue must be a different one.

**Comment by lemavri** [comment] 2015-07-31 18:06
According to one of our users, the problem is related to a change in permissions in El Capitan. It appears that applications are unable to being installed under `/usr/lib`, which is the case of Prey. Instead, they should be installed under `/usr/local/lib`. I will have to look further into the issue.

**Comment by crockpotveggies** [comment] 2015-08-12 17:45
+1

**Comment by lookfirst** [comment] 2015-09-18 07:43
Yup, my console log is being filled up with error messages:

9/18/15 12:42:51.594 AM com.apple.xpc.launchd[1]: (com.prey.agent[68228]) Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /usr/lib/prey/current: 15A282a: xpcproxy + 12028 [1353][19011403-4854-3CCD-9FCF-49C36302EB40]: 0x2
9/18/15 12:42:51.594 AM com.apple.xpc.launchd[1]: (com.prey.agent) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by lookfirst** [comment] 2015-09-18 07:44
Screenshot of install failure with 1.4.1: http://take.ms/1LcaW

**Comment by stewacide** [comment] 2015-09-30 14:25
This is because of the new rootless / system integrity model. Look in /Library/SystemMigration/History/ and you'll find where Prey was moved on installing El Capitan: seems it hasn't been working for me for about a month, since I installed the public beta. Good thing my Macbook wasn't stolen in that time!!!

Hopefully the developers find a work around.

**Comment by wachunei** [comment] 2015-10-01 15:51
<img width="732" alt="screen shot 2015-10-01 at 12 40 40 pm" src="https://cloud.githubusercontent.com/assets/1024246/10225767/a731d43c-683a-11e5-99ef-14641b11fd68.png">

I don't know if this is related at all but MacTeX distribution had to [https://tug.org/mactex/UpdatingForElCapitan.pdf](release a guide) to link correctly the binaries used in software to the right paths in El Capitan. Could this be a way to workaround this by specifying binaries in a different location?

**Comment by lemavri** [comment] 2015-10-02 14:40
The fix to this issue will be included in the release 1.4.2, which is about to be published.

**Closed by lemavri** 2015-10-02 14:40 UTC
Labels: bug, priority: high

**Comment by beeatriz** [comment] 2015-10-02 15:35
Avisa cuando salga

2015-10-02 11:40 GMT-03:00 Mauricio Schneider <notifications@github.com>:

**Comment by asadowski** [comment] 2015-10-04 01:47
So is prey in `/usr/local/lib` now?

**Comment by lemavri** [comment] 2015-10-04 01:48
Yes, it is.

**Comment by escapone** [comment] 2016-08-01 14:56
it is impossible to install EL CAPITAN mac on prey, it sais outdated config file all time. Anyone a solution?
